# Generated by Django 4.1 on 2022-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hardcopy_lent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
