# Generated by Django 4.1 on 2022-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_author_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourited',
            field=models.ManyToManyField(to='core.book'),
        ),
    ]
